#!/bin/bash -

# created date: 2020.09.16
# author: seongcheol jeon
# email: saelly55@gmail.com

#set -o nounset                              # Treat unset variables as an error

export DEF_HOUDINI_VERSION="${HVERSION}"
export DEF_FXUSER="${FXUSER}"

export DEF_OPT_DIR="opt"
export DEF_HOU_BRG="hfs"

#export DEF_FXHOME=`dirname "${BASE_DIR}"`
export DEF_FXHOME="${FXHOME_DIR}"
export DEF_FXHOME_USER_BRIDGE_DIR="users"
export DEF_FXHOME_COMMON_BRIDGE_DIR="common"

export FXSCRIPT="scripts"
export FXSCRIPT_ROOT="${HRUN_DIR}"
#export FXSCRIPT_FULL_DIR="${DEF_FXHOME}/${FXSCRIPT}/${FXSCRIPT_ROOT}"
export FXSCRIPT_FULL_DIR="${BASE_DIR}/${FXSCRIPT_ROOT}"

#export PYTHONPATH="${FXSCRIPT_FULL_DIR}"
export PYTHONPATH="${PYTHONPATH}:${FXSCRIPT_FULL_DIR}"

# 디렉토리 이름
FXSCRIPT_CHILD_MODULES="modules"
FXSCRIPT_CHILD_MODULES_ENV="environment"
FXSCRIPT_CHILD_MODULES_DEF="default"

FXSCRIPT_CHILD_HRUN="hrun"
FXSCRIPT_CHILD_HRUN_ARGS="hrun_args"

FXSCRIPT_CHILD_HRENDER="hrender"
FXSCRIPT_CHILD_HRENDER_ARGS="hrender_args"
FXSCRIPT_CHILD_HRENDER_SETPARM="hrender_set_parm"
#

export FXSCRIPT_FULL_MODULES_DIR="${FXSCRIPT_FULL_DIR}/${FXSCRIPT_CHILD_MODULES}"
export FXSCRIPT_FULL_MODULES_ENV_DIR="${FXSCRIPT_FULL_MODULES_DIR}/${FXSCRIPT_CHILD_MODULES_ENV}"
export FXSCRIPT_FULL_MODULES_DEF_DIR="${FXSCRIPT_FULL_MODULES_DIR}/${FXSCRIPT_CHILD_MODULES_DEF}"

export FXSCRIPT_FULL_HRUN_DIR="${FXSCRIPT_FULL_DIR}/${FXSCRIPT_CHILD_HRUN}"
export FXSCRIPT_FULL_HRUN_ARGS_DIR="${FXSCRIPT_FULL_HRUN_DIR}/${FXSCRIPT_CHILD_HRUN_ARGS}"

export FXSCRIPT_FULL_HRENDER_DIR="${FXSCRIPT_FULL_DIR}/${FXSCRIPT_CHILD_HRENDER}"
export FXSCRIPT_FULL_HRENDER_ARGS_DIR="${FXSCRIPT_FULL_HRENDER_DIR}/${FXSCRIPT_CHILD_HRENDER_ARGS}"
export FXSCRIPT_FULL_HRENDER_SETPARM_DIR="${FXSCRIPT_FULL_HRENDER_DIR}/${FXSCRIPT_CHILD_HRENDER_SETPARM}"


unset FXSCRIPT_CHILD_MODULES FXSCRIPT_CHILD_MODULES_ENV FXSCRIPT_CHILD_MODULES_DEF FXSCRIPT_CHILD_HRUN FXSCRIPT_CHILD_HRUN_ARGS FXSCRIPT_CHILD_HRENDER FXSCRIPT_CHILD_HRENDER_ARGS FXSCRIPT_CHILD_HRENDER_SETPARM

echo "Variables Initialized..."

